
name: Publish package

on:
  push:
    tags:
    - 'v*'

jobs:
  create-release:
    name: Create new release
    runs-on: ubuntu-latest
    steps:
      - name: Publish
        uses: toitlang/pkg-publish@v0.1.6
        with:
          tag: ${{ github.ref_name }}
          repository: ${{ github.repository }}
