
name: Publish package

on:
  push:
    tags:
    - 'v*'

jobs:
  create-release:
    name: Create new release
    runs-on: ubuntu-latest
    steps:
      - name: Publish
        uses: toitlang/pkg-publish@v0.1.3
        with:
          tag: v1.0.6
          repository: toitware/toit-A3967
